/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RepliesRequestBuilderNavigationMetadata, RepliesRequestBuilderRequestsMetadata, type RepliesRequestBuilder } from './replies/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/chats/{chat-id}/messages/{chatMessage-id}
 */
export interface ChatMessageItemRequestBuilder extends BaseRequestBuilder<ChatMessageItemRequestBuilder> {
    /**
     * Provides operations to manage the replies property of the microsoft.graph.chatMessage entity.
     */
    get replies(): RepliesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatMessageItemRequestBuilderUriTemplate = "{+baseurl}/me/chats/{chat%2Did}/messages/{chatMessage%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatMessageItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatMessageItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    replies: {
        requestsMetadata: RepliesRequestBuilderRequestsMetadata,
        navigationMetadata: RepliesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
