/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MessagesRequestBuilderNavigationMetadata, MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/chats/{chat-id}
 */
export interface ChatItemRequestBuilder extends BaseRequestBuilder<ChatItemRequestBuilder> {
    /**
     * Provides operations to manage the messages property of the microsoft.graph.chat entity.
     */
    get messages(): MessagesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatItemRequestBuilderUriTemplate = "{+baseurl}/me/chats/{chat%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
        navigationMetadata: MessagesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
