/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatsRequestBuilderNavigationMetadata, type ChatsRequestBuilder } from './chats/index.js';
// @ts-ignore
import { MailFoldersRequestBuilderNavigationMetadata, MailFoldersRequestBuilderRequestsMetadata, type MailFoldersRequestBuilder } from './mailFolders/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * The chats property
     */
    get chats(): ChatsRequestBuilder;
    /**
     * Provides operations to manage the mailFolders property of the microsoft.graph.user entity.
     */
    get mailFolders(): MailFoldersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/me";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MeRequestBuilderNavigationMetadata: Record<Exclude<keyof MeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chats: {
        navigationMetadata: ChatsRequestBuilderNavigationMetadata,
    },
    mailFolders: {
        requestsMetadata: MailFoldersRequestBuilderRequestsMetadata,
        navigationMetadata: MailFoldersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
