/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatItemRequestBuilderNavigationMetadata, type ChatItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/chats
 */
export interface ChatsRequestBuilder extends BaseRequestBuilder<ChatsRequestBuilder> {
    /**
     * Gets an item from the ApiSDK.me.chats.item collection
     * @param chatId The unique identifier of chat
     * @returns {ChatItemRequestBuilder}
     */
     byChatId(chatId: string) : ChatItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatsRequestBuilderUriTemplate = "{+baseurl}/me/chats";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatsRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byChatId: {
        navigationMetadata: ChatItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["chat%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
